//GET STANDING
export const GET_STANDINGS = 'GET_STANDINGS';
export const GET_STANDINGS_SUCCESS = 'GET_STANDINGS_SUCCESS';
//GET MATCHES 
export const GET_MATCHES = 'GET_MATCHES';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';

export const GET_FIXTURE_PICKS = 'GET_FIXTURE_PICKS';
export const GET_FIXTURE_PICKS_SUCCESS = 'GET_FIXTURE_PICKS_SUCCESS';